### ISSUE TITLE
is this functional?

### ISSUE THREAD

**Issue by tmpvar** [kcuzner/teensy-swd#1]
I love this idea!  What is required to use this as a programmer?

**Comment by kcuzner** [comment]
It isn't quite working yet. I've been working on it during the weekends, but I haven't yet managed to get it to talk to a device :disappointed:. My test device might be damaged (first QFN I've ever hand-soldered) since my SWD commands appear valid on the oscilloscope, so I'm going to try programming my device with a working SWD programmer (it's in the mail).

What remains after I managed to get it to communicate is:
- Setting up the bus initialization sequence over USB. Right now it's hardcoded.
- Setting up the host software to issue flash write commands based on device and an intel hex file (or an elf binary...I haven't decided yet).

I'd like to expand it further than that, but these are my short term objectives. An existing solution is the [CMSIS-DAP](https://github.com/mbedmicro/CMSIS-DAP) firmware (supported by openocd), but it doesn't support the MK20DX256VLH7 used in the Teensy 3.1. I've considered writing the appropriate bootloader for that, but at the time I thought it might just be simpler to complete this project (not so sure now).

**Comment by tmpvar** [comment]
ah, I'm staring at a STM32F4, trying to figure out how to get some code onto it.

Are you using openocd to communicate with the teensy?  If so, can you share the command line that you are using?

**Comment by kcuzner** [comment]
I'm not. I'm becoming more and more convinced that CMSIS-DAP is the way to go rather than something like this. I may end up just modifying that to work with the Teensy 3.1 so that it can be used with openocd.

As for getting code onto your chip, I've managed to ascertain the following steps being necessary:
- Obtain a JTAG/SWD dongle compatible with openocd. I know the [buspirate](http://dangerousprototypes.com/docs/Bus_Pirate) and [Segger J-Link](https://www.segger.com/jlink-debug-probes.html) can function as both using openocd. A list of hardware can be found [here](http://openocd.sourceforge.net/doc/html/Debug-Adapter-Hardware.html). Porting the CMSIS-DAP firmware to a Teensy 3.1 would also make that into a dongle.
- Connect the dongle to the JTAG/SWD port on your device. You may need a level shifter.
- Use openocd to download the program. From what I've read, this works by running openocd which talks to your device and then using telnet to connect to openocd's server and issue commands such as "flash write_image" which will tell openocd to issue flash write commands.

I found what looks like a useful STM32F4 programming tutorial here: http://www.triplespark.net/elec/pdev/arm/stm32.html.
